[package]
name = "wavexp"
version = "0.1.0"
edition = "2021"

[dependencies]
const_format = "0.2.30"
js-sys = "0.3.60"
uuid = { version = "1.2.2", features = ["v4", "js"] }
wasm-bindgen = "0.2.83"
web-sys = { version = "0.3.60", features = [
	"CanvasRenderingContext2d",
	"ImageData",
	"Document",
	"Element",
	"HtmlCanvasElement",
	"AudioContext",
	"OscillatorNode",
	"OscillatorOptions",
	"GainNode",
	"GainOptions",
	"AudioDestinationNode",
	"AudioParam",
	"AnalyserNode",
	"Path2d",
	"DomRect",
	"TextMetrics",
	"OscillatorType",
	"NodeList",
	"Node"
]}
yew = { version = "0.20.0", features = ["csr"] }
