[package]
name = "wavexp-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.64"
wasm-bindgen = "0.2.83"
web-sys = { version = "0.3.64", features = [
	"Document",
	"CanvasRenderingContext2d",
	"HtmlCanvasElement",
	"Element",
]}
yew = "0.20.0"
