[package]
name = "wavexp"
version = "0.1.0"
edition = "2021"

[dependencies]
wavexp-utils.path = "../wavexp-utils"
yew.workspace = true
js-sys.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys.workspace = true
hound.workspace = true
macro_rules_attribute.workspace = true

[lints]
workspace = true
